'*.{ts,tsx,js}':
  - 'eslint --cache --cache-location ./node_modules/.cache/.eslintcache'
  - 'prettier --loglevel warn --cache --write'
'*.{json,yml,scss}': 'prettier --loglevel warn --cache --write'
